### Variables
@baseUrl = http://localhost:3000


### Health Check
GET {{baseUrl}}/health

### Create User 1 (Auto-connect Online)
POST {{baseUrl}}/api/users/create
Content-Type: application/json

{
  "username": "Chandan",
  "autoConnect": true
}

### Create User 2 (Auto-connect Online)
POST {{baseUrl}}/api/users/create
Content-Type: application/json

{
  "username": "Amit",
  "autoConnect": true
}


### Get All Users
GET {{baseUrl}}/api/users

### Check User Connection Status (User ID 2)
GET {{baseUrl}}/api/users/1/status

### Check User Connection Status (User ID 4)
GET {{baseUrl}}/api/users/4/status
