### Variables
@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiYW1pdCIsImlhdCI6MTc2NjY4NjI0MSwiZXhwIjoxNzY2NzcyNjQxfQ.mNLvfFdo89c5735FfXXmWcfosXVvaVG63dfx-BAp4Ss

### Health Check
GET {{baseUrl}}/health

### Create User 1 (Auto-connect Online)
POST {{baseUrl}}/api/users/create
Content-Type: application/json

{
  "username": "Pablo"
}

### Create User 2 (Auto-connect Online)
POST {{baseUrl}}/api/users/create
Content-Type: application/json

{
  "username": "Amit"
}

### Get All Users
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}

### Get All Online Users
GET {{baseUrl}}/api/users/online